# Generated by Django 5.0.7 on 2024-07-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='peso',
            field=models.CharField(default=123123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='precio',
            field=models.CharField(default=123123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
