# Generated by Django 5.0.7 on 2024-07-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_instrumentos_peso_instrumentos_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentos',
            name='peso',
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='stock',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
