# Generated by Django 5.0.7 on 2024-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_instrumentos_peso_instrumentos_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
