# Generated by Django 5.0.7 on 2024-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_instrumentos_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='peso',
            field=models.CharField(default=666, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
