# Generated by Django 5.0.7 on 2024-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_instrumentos_peso_alter_instrumentos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.FloatField(),
        ),
    ]
